data:
    dataset: "Fusion"
    image_size: 128
    channels: 3
    num_workers: 32
    conditional: True
    mask: True
    edge: True

path:
    log: "logs"
    tb_logger: "tb_logger"
    results: "results"
    checkpoint: "checkpoint"

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2 
    attn_resolutions: [32, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

weight:
    in_channels: 7
    out_ch: 1 
    ch: 32
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [32, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 1
    batch_size: 1
    n_epochs: 37042
    n_iters: 2000000
    snapshot_freq: 5000
    validation_freq: 2000
    ckpt_freq: 20000

sampling:
    batch_size: 1
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001
